# Generated by Django 6.0.1 on 2026-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('y', 'learned'), ('n', 'learning')], max_length=1, null=True),
        ),
    ]
