# Generated by Django 6.0.1 on 2026-01-13 14:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_contactmessage_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NP', unique=True, verbose_name='Phone Number'),
        ),
    ]
