# Generated by Django 6.0.1 on 2026-01-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_options_skill_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['name']},
        ),
    ]
