# Generated by Django 6.0.1 on 2026-01-13 08:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+9779888888888', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
